### PR TITLE
pk-client: Fix use-before-set of PkProgress on cancellation and rework refcounting

### PR DESCRIPTION
**Pull request by pwithnall**
This fixes:
 * https://github.com/PackageKit/PackageKit/issues/665
 * https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2331

See the commit messages for details on the changes.

I’ve tested this using `meson test` (under `G_DEBUG=fatal-criticals gdb` and `valgrind`), and by smoketesting gnome-software.

### CODE REVIEW

**Comment by ximion** [comment]
First glance looks good, I'll look at this in detail tomorrow or today!

**Comment by sidt4** [comment]
I cannot reproduce this issue with this fix, after using for a couple of hours.

But, we're facing https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2333 now.

**Comment by sidt4** [comment]
Can we get this reviewed / committed so distros can backport it ( unless we're planning a new release soon ) ? I cannot use `gnome-software` as it deadlocks in a lot of normal user actions, and I don't want to manually patch my systems.

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Conan-Kudo** [comment]
@ximion Can you please double-check this? I intend to merge this in the next couple of days...

**Comment by sidt4** [comment]
If possible, it would be nice to a unit test for this MR. ( **fail:** timeout due to deadlock, **pass:** no timeout )

**Comment by ximion** [comment]
Sorry for the delay, the amount of plates that I currently need to keep spinning is a bit too much...
Things will get done eventually, but it takes some time.

The patch looked good and worked without issues in testing :-) I didn't even have any style nitpicks. Thanks @pwithnall!

**Pull request merged**
