### PR TITLE
Revert "Enable testing on FreeBSD CI"

### PR DESCRIPTION
**Pull request by Conan-Kudo**
The tests are currently failing and there's been no progress yet on a fix. Drop testing on this for now while we wait for this to be resolved.

This reverts commit 45dc514fb5fb4e5b4118334a710d6e23cea8af07.

cc: @arrowd

### CODE REVIEW

**Comment by arrowd** [comment]
As I wrote in https://github.com/PackageKit/PackageKit/pull/632#issuecomment-1578688750 there is no problem with FreeBSD CI. To the contrary, it highlighted a problem with a recent commit.

**Comment by Conan-Kudo** [comment]
@ximion did this slightly differently in 0f122562daa1062ba99dc4c569ecca1f87cd9053, so I'm closing this.

**Comment by ximion** [comment]
Whoops, sorry, I hadn't seen this PR at all for some reason! Otherwise I would have merged this instead.

**Comment by arrowd** [comment]
I feel like I being ignored. I left multiple comments (https://github.com/PackageKit/PackageKit/pull/632#issuecomment-1578688750 https://github.com/PackageKit/PackageKit/pull/632#issuecomment-1585591894 https://github.com/PackageKit/PackageKit/pull/632#issuecomment-1651027443 ) and even a PR https://github.com/PackageKit/PackageKit/pull/641 indicating that there is no problem with FreeBSD CI. Yet you still disable part of FreeBSD CI rather than fixing the root problem. If my understaning is wrong, could you please at least explain that to me?

**Comment by Conan-Kudo** [comment]
You are not being ignored, but neither @ximion nor I have a fix for this, and he wanted to make a release. Thus he did that so he could make a "green" release.

If you can figure out a fix for the assertions issue, that'd be great. I would be happy to enforce assertions on Linux and FreeBSD once it's fixed too.

**Comment by arrowd** [comment]
I don't have free slots for that, unfortunately. Maybe @pwithnall who introduced the breaking commit has the time for that?

**Comment by pwithnall** [comment]
Afraid not, sorry.

**Pull request closed without merging**
