### PR TITLE
Fix zypp compiler errors and warnings

### LINKED ISSUE #692: Build failure ( zypp backend )
Compiled on `Debian unstable`:

```
$ ninja
[230/231] Compiling C++ object backends/zypp/libpk_backend_zypp.so.p/pk-backend-zypp.cpp.o
../backends/zypp/pk-backend-zypp.cpp:637:1: warning: no previous declaration for ‘gboolean zypp_logging()’ [-Wmissing-declarations]
  637 | zypp_logging ()
      | ^~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:683:1: warning: no previous declaration for ‘gboolean zypp_is_development_repo(zypp::RepoInfo)’ [-Wmissing-declarations]
  683 | zypp_is_development_repo (RepoInfo repo)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:692:1: warning: no previous declaration for ‘gboolean zypp_is_valid_repo(PkBackendJob*, zypp::RepoInfo)’ [-Wmissing-declarations]
  692 | zypp_is_valid_repo (PkBackendJob *job, RepoInfo repo)
      | ^~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:713:1: warning: no previous declaration for ‘zypp::ResPool zypp_build_pool(zypp::ZYpp::Ptr, gboolean)’ [-Wmissing-declarations]
  713 | zypp_build_pool (ZYpp::Ptr zypp, gboolean include_local)
      | ^~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:774:1: warning: no previous declaration for ‘zypp::target::rpm::RpmHeader::constPtr zypp_get_rpmHeader(const std::string&, zypp::Edition)’ [-Wmissing-declarations]
  774 | zypp_get_rpmHeader (const string &name, Edition edition)
      | ^~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:790:1: warning: no previous declaration for ‘PkGroupEnum get_enum_group(const std::string&)’ [-Wmissing-declarations]
  790 | get_enum_group (const string &group_)
      | ^~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:845:1: warning: no previous declaration for ‘void zypp_get_packages_by_name(const gchar*, zypp::ResKind, std::vector<zypp::sat::Solvable>&, gboolean)’ [-Wmissing-declarations]
  845 | zypp_get_packages_by_name (const gchar *package_name,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:867:1: warning: no previous declaration for ‘void zypp_get_packages_by_file(zypp::ZYpp::Ptr, const gchar*, std::vector<zypp::sat::Solvable>&)’ [-Wmissing-declarations]
  867 | zypp_get_packages_by_file (ZYpp::Ptr zypp,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:899:1: warning: no previous declaration for ‘bool zypp_package_is_local(const gchar*)’ [-Wmissing-declarations]
  899 | zypp_package_is_local (const gchar *package_id)
      | ^~~~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:920:1: warning: no previous declaration for ‘zypp::sat::Solvable zypp_get_package_by_id(const gchar*)’ [-Wmissing-declarations]
  920 | zypp_get_package_by_id (const gchar *package_id)
      | ^~~~~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:985:1: warning: no previous declaration for ‘zypp::RepoInfo zypp_get_Repository(PkBackendJob*, const gchar*)’ [-Wmissing-declarations]
  985 | zypp_get_Repository (PkBackendJob *job, const gchar *alias)
      | ^~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp:1175:1: warning: no previous declaration for ‘void zypp_emit_filtered_packages_in_list(PkBackendJob*, PkBitfield, const std::vector<zypp::sat::Solvable>&)’ [-Wmissing-declarations]
 1175 | zypp_emit_filtered_packages_in_list (PkBackendJob *job, PkBitfield filters, const vector<sat::Solvable> &v)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp: In function ‘void zypp_backend_finished_error(PkBackendJob*, PkErrorEnum, const char*, ...)’:
../backends/zypp/pk-backend-zypp.cpp:1803:35: warning: function ‘void zypp_backend_finished_error(PkBackendJob*, PkErrorEnum, const char*, ...)’ might be a candidate for ‘gnu_printf’ format attribute [-Wsuggest-attribute=format]
 1803 |         buffer = g_strdup_vprintf (format, args);
      |                  ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../backends/zypp/pk-backend-zypp.cpp: In function ‘void pk_backend_upgrade_system_thread(PkBackendJob*, GVariant*, gpointer)’:
../backends/zypp/pk-backend-zypp.cpp:3576:23: warning: unused variable ‘restart’ [-Wunused-variable]
 3576 |         PkRestartEnum restart = PK_RESTART_ENUM_NONE;
      |                       ^~~~~~~
../backends/zypp/pk-backend-zypp.cpp: In function ‘void backend_what_provides_thread(PkBackendJob*, GVariant*, gpointer)’:
../backends/zypp/pk-backend-zypp.cpp:3846:62: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
 3846 |                                                              (const gpointer) make<ResObject>(*it)->summary().c_str (),
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[231/231] Linking target backends/zypp/libpk_backend_zypp.so
```

### PR DESCRIPTION
**Pull request by sidt4**
Refer commit log.

Closes #692

### CODE REVIEW

**Comment by sidt4** [comment]
Can this get a review ?

The build breaks in openSUSE Tumbleweed without this patch.

**Comment by Bqleine** [comment]
Can confirm this fixes the zypp backend build. Could you please review this @Conan-Kudo?

**Review by Conan-Kudo — APPROVED** [review]

**Comment by Bqleine** [comment]
Thanks!

**Pull request merged**
