### PR TITLE
Use translation for 'command not found'

### PR DESCRIPTION
**Pull request by gitlab-user**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
This PR is probably not needed and can be closed since #501 is the proper fix, right?

**Comment by hughsie** [comment]
Agree. Thanks!

**Comment by gitlab-user** [comment]
@AsciiWolf @hughsie No, #501 fixes only C code, this pull request fixes shell script to translate when in not interactive mode too

**Comment by AsciiWolf** [comment]
Oops! Sorry. @hughsie Feel free to reopen then.

**Comment by AsciiWolf** [comment]
Could this PR please be reopened?

**Pull request closed without merging**
