### PR TITLE
Add backend/pisi

### PR DESCRIPTION
**Pull request by erkanisik1**

### CODE REVIEW

**Comment by ximion** [comment]
Will you be the maintainer of this backend, test it and keep it up-to-date with upstream Pisi and PackageKit itself?

**Comment by erkanisik1** [comment]
As the pisilinux team, we will certainly support. We became aware that it was removed from the backend when one of our users alerted us.

**Comment by ximion** [comment]
It was removed more than 3 years ago, and as far as I remember it wasn't very well maintained back then and we didn't have someone to contact or fix bugs.

While we maintain PackageKit, we lack the expertise to update and fix every single backend and keep up with upstream changes. That's why each backend also has a maintainer that takes care of that for the respective distribution or PM.

If you (and the Pisilinux team) commit to maintaining the backend from this point forward, I am happy to merge this. Besides formatting issues, the code looks okay.
It will be one of the few backends that actually utilize the spawn interface for backends that PK provides, so may need some more testing to ensure nothing broke on that front in three years.

**Comment by erkanisik1** [comment]
Thank you for your prompt response. I understand the challenge of maintaining PackageKit consistently and recognize the difficulty in providing sustained support for each backend.

On behalf of the Pisilinux team, we are ready to commit to the necessary maintenance and support for this backend. We will do our best to provide the necessary updates and tests for the backend that was removed three years ago, ensuring it functions seamlessly with PackageKit. This includes thorough testing to ensure the spawn interface works as intended.

We are also prepared to make the necessary adjustments concerning the formatting issues you've pointed out. We hope that this collaboration will be beneficial both for Pisilinux users and the PackageKit community at large.

Thank you once again for your positive outlook. We look forward to your reply.

Best regards,

Pisilinux Team

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
@erkanisik1 Please update the reference to the pisi backend maintainer in `AUTHORS`

**Comment by ximion** [comment]
> On behalf of the Pisilinux team, we are ready to commit to the necessary maintenance and support for this backend. We will do our best to provide the necessary updates and tests for the backend that was removed three years ago, ensuring it functions seamlessly with PackageKit. This includes thorough testing to ensure the spawn interface works as intended.

Awesome, that's what I needed to know :-)
Once this PR updates the AUTHORS file as well, as requested by @Conan-Kudo, I think this is good to go!

**Review by Conan-Kudo — APPROVED** [review]

**Comment by joebonrichie** [comment]
I've consequently unrelatedly also been working on improving the pisi backend for the `eopkg` fork of PiSi in Solus as we investigate replacing solus-sc with gnome-software/discover.

https://github.com/joebonrichie/PackageKit/blame/pisi/backends/pisi/pisiBackend.py

Admitably, some of it is quite hacky and it's mostly been focused on getting gnome-software working as intended; but, there is `get-details-local` support, filters support, fixed calls to accept multiple packages instead of just one, mostly fixed status reporting, etc.

Due to `eopkg` being a fork, not all of it will be applicable to pisilinux (e.g. autoremove support, CVE reporting) however, @erkanisik1 feel free to take what is there if it helps.

In terms of what needs to be done: less hacky status reporting, only-download support, Progress/UI callbacks and cleanup some of the old FIXMEs.

**Pull request merged**
