### PR TITLE
aptcc: fix serveral bugs relating to installing and searching packages

### PR DESCRIPTION
**Pull request by liushuyu**
This Pull Request will fix a few bugs relating to installing and searching packages when using the `aptcc` backend, namely:

- When installing a package that is not the latest available version, the backend will either treat the package as does not exist or install a version that is different than requested
- When downgrading a package, the backend will incorrectly reinstall the package using the current version instead of performing a downgrade to the specified version
- When searching/resolving a package or package ID, the backend will fail to list all the available versions or just fail to list anything

### CODE REVIEW

**Comment by dantti** [comment]
the code looks fine, any thoughts? @ximion @julian-klode

**Comment by julian-klode** [comment]
I think I'd prefer if the backend refused to install a version that is not the candidate, and not allow downgrades. You can do those things in APTs to some degree of success, but it's all tricky, and downgrades might just fail; I don't see reason to expose this at a higher level.

**Comment by liushuyu** [comment]
> I think I'd prefer if the backend refused to install a version that is not the candidate, and not allow downgrades. You can do those things in APTs to some degree of success, but it's all tricky, and downgrades might just fail; I don't see reason to expose this at a higher level.

I am afraid you misunderstood. The root cause here is that the backend only reports one version to PackageKit. This would lead to disastrous issues where, if an update transaction would _downgrade_ a certain package due to dependency, PackageKit would possibly destroy the system because an incorrect version is selected.

Also, previously, listing other candidate versions of a package is impossible. Unless this is intentional, I could only see it as a bug.

**Comment by julian-klode** [comment]
I think only reporting one version is sort of correct; picking the right alternative cannot (should not) be done sensibly by a frontend. PackageKit should not be trying to downgrade packages. It should expose candidate and installed versions; the candidate is never a downgrade (unless forced by extreme pinning).

There are no other candidate versions. Candidate version is the term that describes the version that apt will install. There is always just one such version per package, and that version is determined by pinning and the installed version.

**Comment by ximion** [comment]
@liushuyu I think a good compromise here is to refuse downgrades, but allow installations of older versions when the package in question wasn't previously installed.
Either way, the current behavior is a bug. Can you please rebase your patch against the current master version of PK?

**Comment by liushuyu** [comment]
> @liushuyu I think a good compromise here is to refuse downgrades, but allow installations of older versions when the package in question wasn't previously installed. Either way, the current behavior is a bug. Can you please rebase your patch against the current master version of PK?

Rebased. I have tested the rebased branch locally, and I did not find any new issues.

**Comment by ximion** [comment]
I couldn't test this yet, but the changes do make sense to me an definitely improve the status quo, even though I don't like that this would actually make downgrades work again in aptcc ;-). Can you squash the two "aptcc: correctly lists all the available package versions" and "aptcc: fix a regression introduced in the last commit" together? (makes NEWS file writing as well as any future bisecting easier).

**Comment by liushuyu** [comment]
> Can you squash the two "aptcc: correctly lists all the available package versions" and "aptcc: fix a regression introduced in the last commit" together? (makes NEWS file writing as well as any future bisecting easier).

Rebased the last two commits and melt them into one.

> I couldn't test this yet, but the changes do make sense to me an definitely improve the status quo, even though I don't like that this would actually make downgrades work again in aptcc ;-). 

The byproduct of fixing package listing is the downgrading being fixed as well. I still think only listing the most recent package version is a bug in downstream developers' eyes (since this backend is the only few that the behaviour deviates from the "majority" of the backends). And you are right, downgrading is not feasible most of the time but on certain occasions, this is unavoidable (e.g. opt-out of a testing repository like Debian backports).

**Comment by ximion** [comment]
Looks good, thank you for the patch!

**Pull request merged**
