### PR TITLE
PkClient: Replace the GSimpleAsyncResult with the GTask API

### PR DESCRIPTION
**Pull request by tintou**
The GSimpleAsyncResult API is deprecated and can be replaced by GTask, also avoid copying the GError when set.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Isn't this an ABI break?

cc: @hughsie @ximion

**Comment by tintou** [comment]
No ABI break here

**Comment by ximion** [comment]
> Isn't this an ABI break?
> 
> cc: @hughsie @ximion

No, API-wise this is fine and the behavior should also match. It's a pretty nice maintenance task, actually - very nice!
I just need a bit of spare time to look over the code in more detail (at first glance, it looked fine).

**Review by Conan-Kudo — APPROVED** [review]

**Comment by sidt4** [comment]
Indeed, that's a much needed change :+1:

**Comment by ximion** [comment]
I finally had time to look into this, and I have no notes - this patch looks good as-is! Pretty awesome!
The one thing I am a bit worried about is subtle behaviour changes that I may not be aware of that this switch might bring, but looking through the docs I didn't find any.
So, there's no reason not to merge this change - thank you for the patch!

**Review by ximion — APPROVED** [review]

**Pull request merged**
