### PR TITLE
alpm: Support replaces with version expressions

### PR DESCRIPTION
**Pull request by aleixpol**
We were just checking filenames, now using alpm_dep_from_string() we
make follow the pkgname<1.0 kind of notation.

### CODE REVIEW

**Comment by aleixpol** [comment]
WIP as it's untested

**Comment by antonio-rojas** [comment]
To test, run
```
sudo pacman -U https://archive.archlinux.org/packages/l/libcanberra/libcanberra-0.30%2B2%2Bgc0620e4-3-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/l/libcanberra/libcanberra-pulse-0.30%2B2%2Bgc0620e4-3-x86_64.pkg.tar.zst
```
and then try to update with `pkcon update`. For me it doesn't seem to work: with the patch, I get
```
Getting updates               [=========================]         
Finished                      [=========================]         
Testing changes               [=========================]         
Finished                      [                         ] (0%)  
The following packages have to be updated:
 mariadb-libs-10.6.5-2.x86_64   MariaDB libraries
Proceed with changes? [N/y]
```
which is absurd, as that package is up to date. Without the patch, I get
```
Getting updates               [=========================]         
Finished                      [=========================]         
Downloading list of packages  [=========================]         
Testing changes               [=========================]         
Finished                      [=========================]         
Fatal error: libcanberra=0.30+2+gc0620e4-3 <- libcanberra-pulse: could not satisfy dependencies
```

**Comment by antonio-rojas** [comment]
The reason why a `mariadb-libs` update shows up is probably that it both provides and replaces `libmariadbclient`. Package replacements shouldn't take provides into account.

**Comment by aleixpol** [comment]
> which is absurd, as that package is up to date.

Addressed.

> Fatal error: libcanberra=0.30+2+gc0620e4-3 <- libcanberra-pulse: could not satisfy dependencies

I get the same now.  Can you point at me which rule should be addressing this?

**Comment by antonio-rojas** [comment]
> I get the same now. Can you point at me which rule should be addressing this?

Not sure I understand the question... current libcanberra package has `replaces: libcanberra-pulse<0.30+2+gc0620e4-4`, so it should be replacing `libcanberra-pulse 0.30+2+gc0620e4-3` and PK shouldn't complain about missing dependencies for it.

**Comment by aleixpol** [comment]
Now it works with the libcanberra test @antonio-rojas provided. Thanks a lot for it!

**Comment by aleixpol** [comment]
Also already merged by archlinux packaging. If nobody complains, I'll merge in a few days. (or maybe next year ha-ha)

**Pull request merged**
