### PR TITLE
FreeBSD backend

### PR DESCRIPTION
**Pull request by arrowd**
This PR implements PackageKit backend for the FreeBSD `pkg`. It is not completely finished, but we're using it for months together with Plasma Discover for basic package management.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Please don't reference tickets that nobody has access to in the commit messages.

**Comment by Conan-Kudo** [comment]
Please don't reference tickets that nobody has access to in the commit messages (e.g. `GOS-413` and `GOS-421`). Instead, please explain the context in the commit message.

**Comment by arrowd** [comment]
Oops, these somehow slipped in.

**Comment by Conan-Kudo** [comment]
Could you please add license headers for code from FreeBSD that is copied into here? In particular, I want to make sure we know that `stolen.c` and `xstring.h` are correctly tracked as from FreeBSD and where in FreeBSD they're from (and the license for them).

**Comment by arrowd** [comment]
Right, I completely forgot about that. The `stolen.*` code also need a lot of trimming, as I sinked most of the code back to our libpkg.

**Comment by arrowd** [comment]
> Are you prepared to sign up for maintaining this backend?

Absolutely, even in my free time.

> quality of the development (which is very good).

Heh, thanks!

**Comment by Conan-Kudo** [comment]
Can you rebase this branch on top of current mainline? It seems @ximion made changes to the core and CI.

**Comment by Conan-Kudo** [comment]
Also, can you add the FreeBSD backend maintainer information to `AUTHORS`?

**Comment by arrowd** [comment]
I have address the raised comments.

**Comment by Conan-Kudo** [comment]
I'm okay landing this as-is, as I'm trusting the code here and your maintenance of this. I don't see anything obvious that would be a problem, and I assume you've qualified this on a FreeBSD system?

**Comment by Conan-Kudo** [comment]
Actually, you might want to adjust the FreeBSD CI to at least build the freebsd backend now.

**Comment by arrowd** [comment]
>  I don't see anything obvious that would be a problem, and I assume you've qualified this on a FreeBSD system?

We're using it internally for several months for now with Plasma Discover. After the next PackageKit release I'll start pushing this downstream too.

> Actually, you might want to adjust the FreeBSD CI to at least build the freebsd backend now.

The backend uses an unreleased libpkg version for now, so enabling the backend on the CI will have to wait. I will do that of course, once the new libpkg lands into FreeBSD repositories.

**Comment by Conan-Kudo** [comment]
Sounds good, I'll merge this now then! Thank you for this work to enable PackageKit on FreeBSD! 😄

**Pull request merged**
