### PR TITLE
Nix: fix build with Nix 2.9.0

### PR DESCRIPTION
**Pull request by bobby285271**
Looks like we need to do this every six weeks, compiles, hope this works.
See also https://github.com/NixOS/nix/commit/a385e51

/cc @matthewbauer @jtojnar

### CODE REVIEW

**Comment by jtojnar** [comment]
I tried building it locally but could not get Nix itself to compile. Do you perhaps have a flake for testing handy?

```patch
diff --git a/pkgs/tools/package-management/nix/default.nix b/pkgs/tools/package-management/nix/default.nix
index 44877c94c25..f5a85858407 100644
--- a/pkgs/tools/package-management/nix/default.nix
+++ b/pkgs/tools/package-management/nix/default.nix
@@ -98,4 +98,9 @@ in lib.makeExtensible (self: {
       sha256 = "sha256-RH77Y4IhbTofNYlLQSGKLL0fJAG9iHSwRNvMEZ4M0VQ=";
     };
   });
+
+  nix_2_9 = lib.lowPrio (common rec {
+    version = "2.9";
+    src = /home/jtojnar/Projects/nix;
+  });
 })
diff --git a/pkgs/tools/package-management/packagekit/default.nix b/pkgs/tools/package-management/packagekit/default.nix
index 66064139f38..d9acc11fb8e 100644
--- a/pkgs/tools/package-management/packagekit/default.nix
+++ b/pkgs/tools/package-management/packagekit/default.nix
@@ -33,12 +33,7 @@ stdenv.mkDerivation rec {
 
   outputs = [ "out" "dev" "devdoc" ];
 
-  src = fetchFromGitHub {
-    owner = "PackageKit";
-    repo = "PackageKit";
-    rev = "30bb82da8d4161330a6d7a20c9989149303421a1";
-    sha256 = "k2osc2v0OuGrNjwxdqn785RsbHEJP3p79PG9YqnVE3U=";
-  };
+  src = /home/jtojnar/Projects/PackageKit;
 
   buildInputs = [
     glib
diff --git a/pkgs/top-level/all-packages.nix b/pkgs/top-level/all-packages.nix
index afcab99ca6a..5344f4d731a 100644
--- a/pkgs/top-level/all-packages.nix
+++ b/pkgs/top-level/all-packages.nix
@@ -9149,7 +9149,7 @@ with pkgs;
 
   p7zip = callPackage ../tools/archivers/p7zip { };
 
-  packagekit = callPackage ../tools/package-management/packagekit { nix = nixVersions.nix_2_8; };
+  packagekit = callPackage ../tools/package-management/packagekit { nix = nixVersions.nix_2_9; };
 
   packetdrill = callPackage ../tools/networking/packetdrill { };
 
```

**Comment by jtojnar** [comment]
Also since the first commit likely will not build with Nix 2.8, the requirements bump should probably be part of it.

**Comment by bobby285271** [comment]
> I tried building it locally but could not get Nix itself to compile

I built this with https://github.com/NixOS/nixpkgs/compare/master...d8bfab65c2d

**Comment by bobby285271** [comment]
Looks like 2.10.x doesn't break compilation of this :thinking:

**Review by matthewbauer — APPROVED** [review]

**Pull request merged**
